const dns = require("node:dns");
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import Footer from "@/components/shared/footer/Footer";
import { Toaster } from "sonner";

const Josefin = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "WanderLust || Best travel booking app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${Josefin.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* Sonner Toaster component */}
        {/* richColors enables the green/red themes for success/error */}
        <Toaster position="top-center" richColors closeButton />

        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
